[2021-08-27 14:45:23,333] - Logger.py] - ERROR: pid does not exist
